### PR TITLE
Fix winners not appearing in category results

### LINKED ISSUE #101: Overall winners are not in category results
**Describe the bug**
Overall winners are not in category results

**To Reproduce**
1. Check winners in general results
2. Search for winners in category results
3. They're not there 👻

**Expected behavior**
All people who received categorised pegs to have there totals listed under each category

### PR DESCRIPTION
**Pull request by Evangelinexx**
Fixes #101

### CODE REVIEW

File: src/lib/services/format-results-service.ts [hunk 1]
```diff
@@ -28,20 +28,22 @@ export class DefaultFormatResultsService implements FormatResultsService {
 		const todayString = today.getFullYear() + '-' + (today.getMonth() + 1) + '-' + today.getDate();
 
 		const winnersData: ResultRow[] = await this.database.returnWinners();
-		let resultsData: ResultRow[] = await this.database.returnResults();
+		const resultsData: ResultRow[] = await this.database.returnResults();
 
 		//Get only people who didn't win in the general results so there are no double ups
-		resultsData = resultsData.filter(x => !winnersData.some(y => y.receiverid == x.receiverid));
+		const losersData = resultsData.filter(x => !winnersData.some(y => y.receiverid == x.receiverid));
```
Comment (jimcullenaus) [inline src/lib/services/format-results-service.ts]: Hahaha, love that variable name!
